apiVersion: v1
kind: Service
metadata:
  name: time-tracker-service
spec:
  selector:
    app: time-tracker-service
  ports:
    - protocol: TCP
      port: 50054
      targetPort: 50054
  type: ClusterIP
